### ISSUE TITLE
Blatant Hypocrisy

### ISSUE THREAD

**Issue by MicrocontrollersDev** [MatthewTGM/Mod-Alternatives#9]
>bitches about complex stealing code and passing it off as his own
>proceeds to steal not only all the evidence but also all the extra commentary and pass it off as your own

**Comment by IRONM00N** [comment]
agreed

**Comment by Kingili22** [comment]
agreed

**Comment by JosephE2** [comment]
so true, little bitch cant stop stealing code

**Comment by Zordlan** [comment]
Fuck you, Matthew.

**Comment by GhqstMC** [comment]
I don't see _that_ much wrong with it but yes Matthew should add citations

**Comment by MicrocontrollersDev** [comment]
> I don't see _that_ much wrong with it but yes Matthew should add citations

it's quite literally a copy paste except rephrased with absolutely no credit given. literally every piece of evidence provided in the SBE one is on my original one. nothing was added, shit was just removed. he even copied stuff like the sunk cost and people you should give money to
